### ISSUE TITLE
--freqnum and --freq not mentioned in README.md

### ISSUE THREAD

**Issue by marianoastor** [bobbypaton/pyQRC#2]
By reading README.md it would seem as if the program is only able to generate coordinates from negative modes. It would be nice to mention --freqnum and --freq, so it's perfectly clear that you can use it with any mode.

**Comment by bobbypaton** [comment]
OK - thanks for the suggestion, will do that!

**Comment by bobbypaton** [comment]
I've added a new example, showing how this functionality can be used to go from planar cyclohexane to two different minima (chair-shaped or twist-boat) depending on which normal mode is initially displaced.
