### ISSUE TITLE
Orca output file could not be identified

### ISSUE THREAD

**Issue by Neon7799** [bobbypaton/pyQRC#4]
Hi, I want to test the claisen_ts.out, which is an Orca output file. When i run it with the following command:python -m pyqrc claisen_ts.out --nproc 4 --freqnum 1, I got error message:AttributeError: 'getoutData' object has no attribute 'NATOMS' . The error is from getFREQS(self, outlines, self.NATOMS, "Gaussian") in pyQRC.py
It looks like pyQRC identified this .out file as a gaussian output file rather than Orca output file. Is there any way I can specify the type of the output file?

**Comment by bobbypaton** [comment]
Sorry - I don't think we support Orca outputs just yet. Will put it on the todo list!

**Comment by rafaelpap** [comment]
Maybe you could try to use 
http://sobereva.com/soft/OfakeG/
The program reads an ORCA output file and produces a "fake" Gaussian output.
I have good experiences reading the "fake" files with molden & Gaussview.
